### ISSUE TITLE
广汽丰田无法运行，提示有中问逗号  

### ISSUE THREAD

**Issue by SunshineTraveller** [WangNingkai/scriptable-scripts#7]
大佬，广汽丰田报错了，但是我检查了下没有中文逗号啊，奇怪。  

const FILE_MGR = FileManager[module.filename.includes('Documents/iCloud~') ? 'iCloud' : 'local']();
await Promise.all(
    ['「小件件」广丰出行.js'].map(async (js) => {
        const REQ = new Request('https://gitee.com/wangningkai/scriptable-scripts/raw/master/gtmc/gtmc.js');
        const RES = await REQ.load();
        FILE_MGR.write(FILE_MGR.joinPath(FILE_MGR.documentsDirectory(), js), RES);
    })
);
FILE_MGR.remove(module.filename);
Safari.open(
    'scriptable:///open?scriptName=' + encodeURIComponent('「小件件」广丰出行')
);

Scriptable 提示 :
Error on line 1: SyntaxError: Invalid character '\uff0c'

![WechatIMG45](https://user-images.githubusercontent.com/18361009/148913136-ccfefb7f-45c6-47f3-aa1e-84c6f2f81a31.jpeg)

**Comment by WangNingkai** [comment]
我TM被人举报了 代码仓仓库被封了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Sunshine ***@***.***&gt;;
发送时间：2022年1月11日(星期二) 下午5:07
收件人："WangNingkai/scriptable-scripts" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[WangNingkai/scriptable-scripts] 广汽丰田无法运行，提示有中问逗号   (Issue #7)
-----------------------------------

 

 
大佬，广汽丰田报错了，但是我检查了下没有中文逗号啊，奇怪。
 
const FILE_MGR = FileManagermodule.filename.includes('Documents/iCloud~') ? 'iCloud' : 'local';
 await Promise.all(
 ['「小件件」广丰出行.js'].map(async (js) =&gt; {
 const REQ = new Request('https://gitee.com/wangningkai/scriptable-scripts/raw/master/gtmc/gtmc.js');
 const RES = await REQ.load();
 FILE_MGR.write(FILE_MGR.joinPath(FILE_MGR.documentsDirectory(), js), RES);
 })
 );
 FILE_MGR.remove(module.filename);
 Safari.open(
 'scriptable:///open?scriptName=' + encodeURIComponent('「小件件」广丰出行')
 );
 
Scriptable 提示 :
 Error on line 1: SyntaxError: Invalid character '\uff0c'
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SunshineTraveller** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件...

**Comment by WangNingkai** [comment]
@SunshineTraveller 现在可以了

**Comment by SunshineTraveller** [comment]
> 我TM被人举报了 代码仓仓库被封了
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："Sunshine ***@***.***&gt;; 发送时间：2022年1月11日(星期二) 下午5:07 收件人："WangNingkai/scriptable-scripts" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[WangNingkai/scriptable-scripts] 广汽丰田无法运行，提示有中问逗号 (Issue #7) ----------------------------------- 大佬，广汽丰田报错了，但是我检查了下没有中文逗号啊，奇怪。 const FILE_MGR = FileManagermodule.filename.includes('Documents/iCloud~') ? 'iCloud' : 'local'; await Promise.all( ['「小件件」广丰出行.js'].map(async (js) =&gt; { const REQ = new Request('https://gitee.com/wangningkai/scriptable-scripts/raw/master/gtmc/gtmc.js'); const RES = await REQ.load(); FILE_MGR.write(FILE_MGR.joinPath(FILE_MGR.documentsDirectory(), js), RES); }) ); FILE_MGR.remove(module.filename); Safari.open( 'scriptable:///open?scriptName=' + encodeURIComponent('「小件件」广丰出行') ); Scriptable 提示 : Error on line 1: SyntaxError: Invalid character '\uff0c' — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

哪个傻屌干的，这鸡儿。。。

**Comment by WangNingkai** [comment]
![c7d6792dec61c51f9b685083c742516](https://user-images.githubusercontent.com/23030927/148914128-d75b9d66-770a-4e72-9833-b23f6b3c8e44.png)

**Comment by SunshineTraveller** [comment]
> 

可以了现在，辛苦大佬
