### ISSUE TITLE
求开放领克的源代码。不混淆的

### ISSUE THREAD

**Issue by PokerMman** [WangNingkai/scriptable-scripts#9]

**Comment by WangNingkai** [comment]
@PokerMman  
![149098840-6ab6d288-529e-4d13-962d-2e2bf8b531a7](https://user-images.githubusercontent.com/23030927/149259573-d4e374c1-fd37-4523-95a7-9b82cac237e1.png)

**Comment by PokerMman** [comment]
github 公开也不行么
求私聊一份源代码- - 我自己维护都可以

**Comment by WangNingkai** [comment]
@PokerMman  没有公开的想法，可以自己开发
